version: '3.8'

services:
  repository-mcp:
    build: .
    container_name: repository-mcp-server
    ports:
      - "${MCP_SERVER_PORT:-3001}:3001"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MCP_SERVER_PORT=${MCP_SERVER_PORT:-3001}
      - NODE_ENV=${NODE_ENV:-production}
    volumes:
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - mcp-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mcp-network:
    driver: bridge